# Generated by Django 2.1.4 on 2018-12-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_deleted', models.IntegerField(default='0', verbose_name='削除フラグ')),
                ('category', models.IntegerField(default='1', verbose_name='カテゴリーID')),
                ('created_at', models.DateTimeField(default='current_date', verbose_name='作成日')),
                ('updated_at', models.DateTimeField(default='current_date', verbose_name='更新日')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリー名')),
                ('is_deleted', models.IntegerField(default='0', verbose_name='削除フラグ')),
            ],
        ),
    ]
