# Generated by Django 2.1.4 on 2018-12-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_deleted', models.IntegerField(default='0', verbose_name='削除フラグ')),
                ('category', models.IntegerField(default='1', verbose_name='カテゴリーID')),
                ('image', models.FileField(default='', upload_to='uploads/images/', verbose_name='ファイル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
    ]
