# Generated by Django 2.1.5 on 2019-01-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/images/', verbose_name='画像'),
        ),
    ]
