# Generated by Django 2.1.4 on 2018-12-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリー名')),
                ('is_deleted', models.IntegerField(default='0', verbose_name='削除フラグ')),
            ],
        ),
    ]
